### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by yoyota** [yoyota/band-daemoon-bot#13]
```
(node:24) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at batchInfo (/usr/src/app/src/utils.js:46:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:24) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by yoyota** [comment]
홈페이지 개편으로 사이트 구조가 변해서 버그 발생

**Comment by yoyota** [comment]
see #16
